### ISSUE TITLE
Using IMU Controller directly

### ISSUE THREAD

**Issue by Belle0412** [vroland/MyoIMUGestureController#1]
Hey vroland,
I am trying to understand your Code for this IMU Gesture Controller. I have seen that firstly  gesture is performed and recorded, afterwards it will be detected. Is there any possibility to do this at the same time. What I mean is for example, to raise my arm, and at this time it will be directly recognized that I am raising my arm. 
I hope you can help me!
Thanks,
Belle

**Comment by vroland** [comment]
You probably have to use other unambigous gestures and another recognition algorithm. So if I was given this task, I would completely rewrite the gesture recognizer.
